# Generated by Django 2.0.4 on 2018-04-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180429_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
